import Produto from "../produto/Produto";

const produtos: Produto[] = [
    {
        id: 1,
        nome: "Apple iPhone 13",
        descricao: "Smartphone Apple iPhone 13 com 128GB de armazenamento.",
        marca: "Apple",
        modelo: "iPhone 13",
        imagem: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-select-2021?wid=470&hei=556&fmt=png-alpha&.v=1645572315917",
        videoReview: "https://www.youtube.com/watch?v=E4p3pXUe6mI",
        nota: 4.8,
        tags: ["smartphone", "apple", "iphone"],
        preco: 6999,
        especificacoes: {},
        precobase: 6999,
        precopromocional: 6499,
        menorpreco: 6499,
        maiorpreco: 6999,
        precomedio: 6749,
    },
    {
        id: 2,
        nome: "Samsung Galaxy S23",
        descricao: "Smartphone Samsung Galaxy S23 com 256GB de armazenamento.",
        marca: "Samsung",
        modelo: "Galaxy S23",
        imagem: "https://images.samsung.com/is/image/samsung/p6pim/br/2302/gallery/br-galaxy-s23-s911-sm-s911bzgdzto-534666792?$650_519_PNG$",
        videoReview: "https://www.youtube.com/watch?v=3xV1mJvwXok",
        nota: 4.7,
        tags: ["smartphone", "samsung", "android"],
        preco: 5999,
        especificacoes: {},
        precobase: 5999,
        precopromocional: 5499,
        menorpreco: 5499,
        maiorpreco: 5999,
        precomedio: 5749,
    },
    {
        id: 3,
        nome: "Sony WH-1000XM5",
        descricao: "Fone de ouvido com cancelamento de ruído Sony WH-1000XM5.",
        marca: "Sony",
        modelo: "WH-1000XM5",
        imagem: "https://m.media-amazon.com/images/I/61+Q6Rh3OQL._AC_SL1500_.jpg",
        videoReview: "https://www.youtube.com/watch?v=8a2zv6srz3I",
        nota: 4.9,
        tags: ["fone de ouvido", "sony", "cancelamento de ruído"],
        preco: 2499,
        especificacoes: {},
        precobase: 2499,
        precopromocional: 2299,
        menorpreco: 2299,
        maiorpreco: 2499,
        precomedio: 2399,
    },
    {
        id: 4,
        nome: "Dell XPS 13",
        descricao: "Notebook Dell XPS 13 com processador Intel Core i7 e 16GB de RAM.",
        marca: "Dell",
        modelo: "XPS 13",
        imagem: "https://i.dell.com/sites/csimages/Video_Imagery/all/xps-13-9310-laptop.jpg",
        videoReview: "https://www.youtube.com/watch?v=J5pJb5KpLrE",
        nota: 4.6,
        tags: ["notebook", "dell", "ultrabook"],
        preco: 10999,
        especificacoes: {},
        precobase: 10999,
        precopromocional: 9999,
        menorpreco: 9999,
        maiorpreco: 10999,
        precomedio: 10499,
    },
    {
        id: 5,
        nome: "Logitech MX Master 3S",
        descricao: "Mouse sem fio Logitech MX Master 3S com design ergonômico.",
        marca: "Logitech",
        modelo: "MX Master 3S",
        imagem: "https://resource.logitech.com/w_800,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/logitech/en/products/mice/mx-master-3s/gallery/mx-master-3s-graphite-gallery-1.png?v=1",
        videoReview: "https://www.youtube.com/watch?v=5z1u5ZasqP4",
        nota: 4.8,
        tags: ["mouse", "logitech", "ergonômico"],
        preco: 599,
        especificacoes: {},
        precobase: 599,
        precopromocional: 549,
        menorpreco: 549,
        maiorpreco: 599,
        precomedio: 574,
    }
];

export default produtos;